/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package loginandregister;
import com.opencsv.CSVWriter;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import javax.swing.JOptionPane;
import loginandregister.EmployeeCSVReader;
/**
 *
 * @author Claire
 */
public class AdminPage extends javax.swing.JFrame {
  private EmployeeCSVReader reader = new EmployeeCSVReader("MotorPH.csv");
  private List<String[]> employeeDataBase = reader.getEmployeeData();
  private String[] employeeData;
    
    /**
     * Creates new form AdminPage
     */
    public AdminPage() {
        initComponents();
        
    }

    
    
    
    
 public void loadEmployeeData(String csvFile) {
    EmployeeCSVReader csvReader = new EmployeeCSVReader(csvFile);
    List<String[]> employeeData = csvReader.getEmployeeData();

    String[] columnNames = {"ID", "Last Name", "First Name", "Birthday", "Address", "Phone Number", "SSS #", "Philhealth #", "TIN #", "Pag-ibig #", "Status", "Position", "Immediate Supervisor", "Basic Salary", "Rice Subsidy", "Phone Allowance", "Clothing Allowance", "Gross Semi-monthly Rate", "Hourly Rate"};

    DefaultTableModel model = new DefaultTableModel(columnNames, 0);

    // Add existing data to the model
    for (String[] row : employeeData) {
        model.addRow(row);
    }

    // Add new data to the model
//    String[] newRow = {"1234", "John", "Doe", "1990-01-01", "123 Main St", "555-555-5555", "123456789", "987654321", "111-111-1111", "222-222-2222", "Active", "Software Engineer", "Jane Doe", "50000", "1000", "500", "200", "25000", "25.00"};
//    model.addRow(newRow);

    jTableDataBase.setModel(model);
}
 
 
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonLogout = new javax.swing.JButton();
        AddEmp = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jButtonCreateRec = new javax.swing.JButton();
        jButtonEditRec = new javax.swing.JButton();
        jButtonDeleteRec = new javax.swing.JButton();
        jTextFieldPosition = new javax.swing.JTextField();
        jTextFieldEmpNum = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonViewAllEmp = new javax.swing.JButton();
        jTextFieldLastName = new javax.swing.JTextField();
        jTextFieldFirstName = new javax.swing.JTextField();
        jTextFieldPhoneNum = new javax.swing.JTextField();
        jTextFieldAddress = new javax.swing.JTextField();
        jTextFieldSupervisor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDataBase = new javax.swing.JTable();
        jButtonViewEmp1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldStatus = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MotorPH");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 170, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Payroll System");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, -1, 20));

        jButtonLogout.setBackground(new java.awt.Color(204, 0, 0));
        jButtonLogout.setText("Logout");
        jButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLogoutActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 20, 80, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 70));

        AddEmp.setText("Add Employee");
        AddEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmpActionPerformed(evt);
            }
        });
        jPanel1.add(AddEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 550, 120, 30));

        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 550, 120, 30));

        jButtonCreateRec.setText("Refresh");
        jButtonCreateRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCreateRecActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCreateRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 650, 150, 30));

        jButtonEditRec.setText("Edit Record");
        jButtonEditRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditRecActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEditRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 600, 150, 30));

        jButtonDeleteRec.setText("Delete Record");
        jButtonDeleteRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteRecActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDeleteRec, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 650, 150, 30));

        jTextFieldPosition.setEditable(false);
        jTextFieldPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPositionActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldPosition, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 250, 30));

        jTextFieldEmpNum.setEditable(false);
        jPanel1.add(jTextFieldEmpNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 70, 30));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Employee Number: ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 20));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Last Name:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, 20));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("First Name:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, 20));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Phone No.:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, -1, 20));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Address:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, 20));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Supervisor:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 70, 20));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Position:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 50, 20));

        jButtonViewAllEmp.setText("View All Employees");
        jButtonViewAllEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewAllEmpActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonViewAllEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 220, 30));

        jTextFieldLastName.setEditable(false);
        jTextFieldLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLastNameActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 250, 30));

        jTextFieldFirstName.setEditable(false);
        jTextFieldFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFirstNameActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 250, 30));

        jTextFieldPhoneNum.setEditable(false);
        jTextFieldPhoneNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPhoneNumActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldPhoneNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 250, 30));

        jTextFieldAddress.setEditable(false);
        jTextFieldAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAddressActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 250, 30));

        jTextFieldSupervisor.setEditable(false);
        jTextFieldSupervisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSupervisorActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldSupervisor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 250, 30));

        jTableDataBase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableDataBase.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableDataBase.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDataBaseMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDataBase);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 870, 600));

        jButtonViewEmp1.setText("View Employee");
        jButtonViewEmp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewEmp1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonViewEmp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 600, 120, 30));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Status:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 50, 20));

        jTextFieldStatus.setEditable(false);
        jTextFieldStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldStatusActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 250, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmpActionPerformed
     CreateEmployee createEmployee = new CreateEmployee();
     createEmployee.setVisible(true);


    }//GEN-LAST:event_AddEmpActionPerformed

    private void jButtonEditRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditRecActionPerformed
        // TODO add your handling code here:
        
        
      DefaultTableModel model = (DefaultTableModel) jTableDataBase.getModel();
        int selectedRowIndex = jTableDataBase.getSelectedRow();
       if(selectedRowIndex!=-1)
       {
           UserAccount user = new UserAccount();
            user.setEmployeeID(jTextFieldEmpNum.getText()); 
            
          EditEmployee editEmployee = new EditEmployee(user);
          editEmployee.setVisible(true);
       }
               
        
    }//GEN-LAST:event_jButtonEditRecActionPerformed

    private void jButtonDeleteRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteRecActionPerformed
        // TODO add your handling code here:
        
        int indexToDelete = Integer.parseInt(jTextFieldEmpNum.getText());
      
        for (int i = 0; i < employeeDataBase.size(); i++) {
                String[] record = employeeDataBase.get(i);
                 
                if (record[0].equals(String.valueOf(indexToDelete))) {
                    employeeDataBase.remove(i);
                    
                  
                    break;
                }
        }
        
        try {
        CSVWriter writer = new CSVWriter(new FileWriter("MotorPH.csv"),',', CSVWriter.NO_QUOTE_CHARACTER);

            for (String[] updatedRecord : employeeDataBase) {
                 writer.writeNext(updatedRecord);
            }
                 writer.close();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(jButtonDeleteRec, "Error writing to file: " + e.getMessage());
            }
          AdminPage admin = new AdminPage();
          admin.loadEmployeeData("MotorPH.csv");   
          
            JOptionPane.showMessageDialog(jButtonDeleteRec, " Record deleted successfully\n Please refresh to update database");
          
          
    }//GEN-LAST:event_jButtonDeleteRecActionPerformed

    private void jTextFieldPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPositionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPositionActionPerformed

    private void jButtonViewAllEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewAllEmpActionPerformed
       loadEmployeeData("MotorPH.csv");
    }//GEN-LAST:event_jButtonViewAllEmpActionPerformed

    private void jTextFieldLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLastNameActionPerformed

    private void jTextFieldFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFirstNameActionPerformed

    private void jTextFieldPhoneNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPhoneNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhoneNumActionPerformed

    private void jTextFieldAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAddressActionPerformed

    private void jTextFieldSupervisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSupervisorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSupervisorActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
         jTextFieldEmpNum.setText("");
         jTextFieldLastName.setText("");
         jTextFieldFirstName.setText("");
         jTextFieldAddress.setText("");
         jTextFieldPhoneNum.setText("");
         jTextFieldSupervisor.setText("");
         jTextFieldPosition.setText("");
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLogoutActionPerformed
        // TODO add your handling code here:
        // temporary
        this.setVisible(false);
        new HomePage().setVisible(true);
    }//GEN-LAST:event_jButtonLogoutActionPerformed

    private void jTableDataBaseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDataBaseMouseClicked
        DefaultTableModel model = (DefaultTableModel) jTableDataBase.getModel();
        int SelectedRowIndex = jTableDataBase.getSelectedRow();
        
         jTextFieldEmpNum.setText(model.getValueAt(SelectedRowIndex, 0).toString());
         jTextFieldLastName.setText(model.getValueAt(SelectedRowIndex, 1).toString());
         jTextFieldFirstName.setText(model.getValueAt(SelectedRowIndex, 2).toString());
         jTextFieldAddress.setText(model.getValueAt(SelectedRowIndex, 4).toString());
         jTextFieldPhoneNum.setText(model.getValueAt(SelectedRowIndex, 5).toString());
         jTextFieldSupervisor.setText(model.getValueAt(SelectedRowIndex, 12).toString());
         jTextFieldPosition.setText(model.getValueAt(SelectedRowIndex, 11).toString());
         jTextFieldStatus.setText(model.getValueAt(SelectedRowIndex, 10).toString());
    }//GEN-LAST:event_jTableDataBaseMouseClicked

    private void jButtonViewEmp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewEmp1ActionPerformed
        UserAccount user = new UserAccount();
user.setEmployeeID(jTextFieldEmpNum.getText());
       

      this.setVisible(false);
      ViewEmployee viewEmployee;
      viewEmployee = new ViewEmployee(user);
      viewEmployee.setVisible(true);
    }//GEN-LAST:event_jButtonViewEmp1ActionPerformed

    private void jTextFieldStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldStatusActionPerformed

    private void jButtonCreateRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCreateRecActionPerformed
        // TODO add your handling code here:
       loadEmployeeData("MotorPH.csv");
    }//GEN-LAST:event_jButtonCreateRecActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEmp;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonCreateRec;
    private javax.swing.JButton jButtonDeleteRec;
    private javax.swing.JButton jButtonEditRec;
    private javax.swing.JButton jButtonLogout;
    private javax.swing.JButton jButtonViewAllEmp;
    private javax.swing.JButton jButtonViewEmp1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDataBase;
    private javax.swing.JTextField jTextFieldAddress;
    private javax.swing.JTextField jTextFieldEmpNum;
    private javax.swing.JTextField jTextFieldFirstName;
    private javax.swing.JTextField jTextFieldLastName;
    private javax.swing.JTextField jTextFieldPhoneNum;
    private javax.swing.JTextField jTextFieldPosition;
    private javax.swing.JTextField jTextFieldStatus;
    private javax.swing.JTextField jTextFieldSupervisor;
    // End of variables declaration//GEN-END:variables
}
